### ISSUE TITLE
Invalid code appears white and blends in with the backgroudn

### ISSUE THREAD

**Issue by scottcorgan** [SalGnt/brackets-theme#5]
For example, I had this code:

``` html
<<strong>Something</strong>
```

I couldn't see the extra `<` because it was white and that killed me.

Any thoughts on that fix?

**Comment by l4ci** [comment]
So you are using https://github.com/l4ci/Br4ckets-Theme ? Because right here is only the theme without the color scheme.

Either way I cant reproduce your error: In both (day and night version) of Br4ckets-Color Scheme I get:

![bildschirmfoto 2013-11-29 um 08 19 02](https://f.cloud.github.com/assets/473100/1643441/d95b8316-58c6-11e3-891b-7c90ddfc448d.png)

So yes the text is white, but sitting on a pink background - which is quite obvious.

**Comment by scottcorgan** [comment]
The pink does show up, but not until I close the other brackets. So while I, typing its white. Do you see the same thing.

If not, I'll just reinstall and see if that fixes it.

—

**Comment by l4ci** [comment]
This is default behavior, sublime doesn't know that this tag is a mistake, until you close the other tag.

I saw this "bug" in other themes as well, so nothing we can do about it I guess.
